cafein/User/urls.py
from django.urls import path
from . import views
from .views import EditProfile
from django.contrib.auth import views as auth_views


app_name = 'user'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/', views.logout_func, name='logout'),
    path('edit/<int:pk>', EditProfile.as_view(), name='edit'),
]

cafein/cafein/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('user', include('User.urls')),
]

cafein/post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.home, name='home'),
]

cafein/User/models.py
from django.db import models

# ここから追加
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.core.mail import send_mail
from django.utils import timezone


# cloudinaryを使う上で必須
import cloudinary

import cloudinary.uploader
import cloudinary.api
from cloudinary.models import CloudinaryField



'''
UserManager とは
->Django の User モデルの管理に必要なクラスのこと。例えば User を作成するためのメソッドなどを管理している
これは Django のモデルを扱うクラスも継承しており、Userモデルの中の objects という変数で管理している

BaseUserManager
->create_user や create_superuser などの関数が定義されており、それらをオーバーライドすることによって username ではなく email での登録をするようにしている

use_in_migrations = True
->このクラスもマイグレーションで管理できるようになる

normalize_email
-> メールアドレスのドメイン部分を小文字にして電子メールアドレスを正規化する
'''
class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        # email を必須にする
        if not email:
            raise ValueError('メールアドレスを入れてください')
        # email で User モデルを作成
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            **extra_fields
            )
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)




'''
PermissionsMixin
->管理者権限周りの機能を追加してくれるクラス。カスタムユーザー作成の際は必須

unique = True
->他のユーザーと被りが出ないようにする

USERNAME_FIELD = 'email'
->email というフィールド でこのプロジェクトの User を一意に判別するという設定ができる
つまり、このフィールド(今回は email)の情報でユーザーを検索すれば、必ず一人のユーザーだけが結果として表示される

REQUIRED_FIELDS = []
->createsuperuserを行うときに必須となるフィールドを指定できまる
しかし、USERNAME_FIELD と password のフィールドについては必ず必須になるので、こちらで指定する必要はない
'''
class User(AbstractBaseUser, PermissionsMixin):
    good_name = models.CharField('ユーザーネーム', max_length=30, unique=True)
    email = models.EmailField('メールアドレス', unique=True)
    is_staff = models.BooleanField('is_staff', default=False)
    is_active = models.BooleanField('is_active', default=True)
    user_description = models.TextField('自己紹介文', blank=True, null=True)
    user_img = models.ImageField('プロフィール画像', upload_to='user_img', default=None)
    # user_img = CloudinaryField('user_img', blank=True, null=True)
    date_joined = models.DateTimeField('date_joined', default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['good_name',]

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

cafein/post/models.py
from django.db import models

# Create your models here.

cafein/User/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

# cloudinary使うなら必須
from cloudinary.forms import CloudinaryFileField

'''
DjangoのデフォルトのUserモデルを利用する場合は付属のUserCreationFormをそのまま使うだけでサインアップ用のフォームを作ることができた。
しかし、今回はカスタムユーザーモデルを作成しているため、新しく設定したフィールドに合わせてユーザー作成のフォームを作る必要がある。これを実現するために、UserCreationForm をオーバーライドした CustomUserCreationFormクラスを作成し、サインアップページを作っていく。
-------------------------------------------------------------------------------------------
デフォルトのUserモデルの場合、django.contrib.auth.models.Userをインポートすることになるが、今回はカスタムユーザーモデルを参照する必要がある。

カスタムユーザーモデルを参照するには get_user_model 関数を使う。この関数ではsettings.pyのAUTH_USER_MODEL(今回はUser.User)に設定したモデルを呼び出す。カスタムユーザーを使っている場合、どのファイルからもこちらの関数を利用することでUserモデルを呼び出すことができるので覚えておく。
'''


class CustomUserCreationForm(UserCreationForm):
    # user_img = CloudinaryFileField(
    #         options={'folder': 'media/user_img', 'tags': 'User'})
    
    class Meta:
        model = get_user_model()
        fields = ('email','good_name',)

cafein/User/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import CustomUserCreationForm
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User
from django.urls import reverse_lazy



'''
forms.pyで作成したCustomUserCreationFormを使って新しいユーザーを作成していく。
フォームの入力データからemailとpassword1の値を取り出し、authenticate関数でユーザーの認証をとっている。認証がうまくいった際には、ユーザーをそのままログインさせてトップページにリダイレクトする処理になっています。
'''

def signup(request):
    if request.user.is_authenticated:
        return redirect('post:login')
    if request.method == 'POST':
        # ユーザーインスタンスを作成
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # ユーザーインスタンスを保存
            new_user = form.save()
            input_username = form.cleaned_data['good_name']
            input_email = form.cleaned_data['email']
            input_password = form.cleaned_data['password1']
            # フォームの入力値で認証できればユーザーオブジェクト、できなければ None を返す
            new_user = authenticate(email=input_email, good_name=input_username, password=input_password)
            if new_user is not None:
                login(request, new_user)
                return redirect('main:profile')
    else:
        form = CustomUserCreationForm()
    return render(request, 'user/signup.html', {'form': form})


# 関数名を logout にしてしまうとエラーとなる(デフォルトで logout が用意されているため)
def logout_func(request):
    logout(request)
    messages.info(request, 'ログアウトしました')
    return redirect('home:home')


class EditProfile(UpdateView, LoginRequiredMixin):
    template_name = 'user/edit.html'
    model = User
    fields = ('email', 'good_name', 'user_description', 'user_img')
    success_url = reverse_lazy('main:profile')

    # fields = ('email', 'good_name', 'user_description', 'user_img')

cafein/post/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'post/home.html')

cafein/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Amatic+SC|Caveat|Indie+Flower|Montserrat|Pacifico|Shadows+Into+Light&display=swap" rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-11/css/all.min.css">


<!-- CSS -->
{% block customCSS %}{% endblock customCSS %}

<!-- JS -->
{% block customJS %}{% endblock customJS %}

<title>Title</title>
</head>
<body>

{% include 'base/header.html' %}

<!-- Main Content -->
{% block content %}{% endblock content %}
    

    

    <footer>
        <hr class="cp_hr01"/>
        <div class="SNS">
            <div class="SNS-icon">
              <a href="#" class="o-btn instagram"><span class="fab fa-instagram"></span></a>
              <a href="#" class="o-btn twitter"><span class="fab fa-twitter"></span></a>
              
            </div>
            
        </div>
    </footer>














<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

cafein/templates/base/header.html
<header>
    <div class="header-top"><nobr>

        <nav role="navigation" class="nav">
            <ul class="nav-items">
                <li class="nav-item">
                    <a href="{% url 'post:home' %}" class="nav-link"><span>Home</span></a>
                </li> 
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link"><span>search</span></a>
                    <nav class="submenu">
                        <ul class="submenu-items">
                            <li class="submenu-item"><a href="#" class="submenu-link">CAFE</a></li>
                            <li class="submenu-item"><a href="#" class="submenu-link">FOOD</a></li>
                            <li class="submenu-item"><a href="#" class="submenu-link">AREA</a></li>
                        </ul>
                    </nav>
                </li> 
                <li class="nav-item dropdown">
                    <a href="{% url 'user:login' %}" class="nav-link"><span>Login</span></a>
                    <nav class="submenu">
                        <ul class="submenu-items">
                            <li class="submenu-item"><a href="#" class="submenu-link">login</a></li>
                            <li class="submenu-item"><a href="#" class="submenu-link">new add</a></li>
                            <li class="submenu-item"><hr class="submenu-seperator" /></li>
                            <li class="submenu-item"><a href="#" class="submenu-link">About</a></li>
                            <li class="submenu-item"><a href="#" class="submenu-link">FAQs</a></li>
                            <li class="submenu-item"><a href="#" class="submenu-link">contact</a></li>
                        </ul>
                    </nav>
                </li>  
            </ul>
        </nav>
        <script src="./script.js"></script></nobr>
    </div>




    
</header>

cafein/templates/post/home.html
{% extends 'base/base.html' %}

{% load static %}

<!-- style CSS -->
{% block customCSS %}
    <link rel="stylesheet" href="{% static 'css/base/style.css' %}">
{% endblock customCSS %}

<!-- style JS -->
{% block customJS %}
    <link rel="stylesheet" href="{% static 'css/base/script.js' %}">
{% endblock customJS %}


{% block content %}


<div class="header-title">
    <H1><nobr>CAFE In</nobr></H1>
    <p><nobr>cafe coffee food cafe coffee food</nobr></p>
</div>

<div class="header-imgs">
    <div class="header-img">

        <div class="main-slide">
            <img src="https://pbs.twimg.com/media/ES5m9o2WkAA3ymo?format=jpg&name=large" alt="">
            <img src="https://pbs.twimg.com/media/ES1kVcWX0Ac8N4n?format=jpg&name=large" alt="">
            <img src="https://pbs.twimg.com/media/ES5hpA9XkAAEm2k?format=jpg&name=large" alt="">
          </div>    
        
    </div>
</div>



<div class="top">
    <div class="container">

        <h3>your favorite cafe</h3>
        <div class="top-top">
            <div class="row">
             <div class="col-2"></div>

             <div class="col-4">
                <a href="#" class="top-link">
                    <img src="https://pbs.twimg.com/media/ESwTkLTX0AAKZrP?format=jpg&name=large" class="img-fluid" alt="Responsive image">
                </a>
             </div>

             <div class="col-2">
                <a href="#" class="top-link">
                    <div class="mediaa">
                        <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTiXSXsAASSX7?format=jpg&name=large" alt="Generic placeholder image"></div>
                    <div class="media">
                        <img class="d-flex align-self-end mr-3" src="https://pbs.twimg.com/media/ESwTy0xXYAAX9Jv?format=jpg&name=large"></div>
                </a>
             </div>

             <div class="col-2">
                <a href="#" class="top-link">
                    <div class="mediaa">
                        <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTou4XgAEpGBX?format=jpg&name=large" alt="Generic placeholder image"></div>   
                    <div class="media">
                        <img class="d-flex align-self-end mr-3" src="https://pbs.twimg.com/media/ESwTou0WkAELPil?format=jpg&name=large" alt="Generic placeholder image"></div>
                </a>
             </div>

             <div class="col-2"></div>
            </div>
        </div>

        <div class="top-center">
            <div class="row">
                <div class="col-2"></div>

                <div class="col-2">
                    <a href="#" class="top-link">
                        <div class="mediaa">
                            <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTnBiXgAATMbJ?format=jpg&name=large" alt="Generic placeholder image"></div>   
                        <p>moji moji moji moji moji moji moji moji mojimoji moji mojimoji moji moji moji moji moji moji moji mojimoji moji moji moji moji moji moji moji moji moji moji moji moji moji</p>
                    </a>
                </div>

                <div class="col-2">
                    <a href="#" class="top-link">
                        <div class="mediaa">
                            <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTkKvXYAAXP8I?format=jpg&name=large" alt="Generic placeholder image"></div>   
                            <p>moji moji moji moji moji moji moji moji mojimoji moji mojimoji moji moji moji moji moji moji moji mojimoji moji moji moji moji moji moji moji moji moji moji moji moji moji</p>
                    </a>
                </div>

                <div class="col-4">
                    <a href="#" class="top-link">
                        <img src="https://pbs.twimg.com/media/ESwTiWvWoAANnvt?format=jpg&name=large" class="img-fluid" alt="Responsive image">
                    </a>
                </div>

                <div class="col-2"></div>
            </div>
        </div>
        
        <div class="top-bottom">
            <form method="get" action="#" class="search_container">
                <input type="text" size="25" placeholder=" search">
                <input type="submit" value="&#xf002">
              </form>
        </div>
    </div>       

</div>

{% endblock content %}

cafein/templates/post/index.html
{% extends 'base/base.html' %}

{% load static %}

<!-- style CSS -->
{% block customCSS %}
    <link rel="stylesheet" href="{% static 'css/base/style.css' %}">
{% endblock customCSS %}

<!-- style JS -->
{% block customJS %}
    <link rel="stylesheet" href="{% static 'css/base/script.js' %}">
{% endblock customJS %}


{% block content %}


<div class="top">
    <div class="container">

        <h3>your favorite cafe</h3>
        <div class="top-top">
            <div class="row">
             <div class="col-2"></div>

             <div class="col-4">
                <a href="#" class="top-link">
                    <img src="https://pbs.twimg.com/media/ESwTkLTX0AAKZrP?format=jpg&name=large" class="img-fluid" alt="Responsive image">
                </a>
             </div>

             <div class="col-2">
                <a href="#" class="top-link">
                    <div class="mediaa">
                        <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTiXSXsAASSX7?format=jpg&name=large" alt="Generic placeholder image"></div>
                    <div class="media">
                        <img class="d-flex align-self-end mr-3" src="https://pbs.twimg.com/media/ESwTy0xXYAAX9Jv?format=jpg&name=large"></div>
                </a>
             </div>

             <div class="col-2">
                <a href="#" class="top-link">
                    <div class="mediaa">
                        <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTou4XgAEpGBX?format=jpg&name=large" alt="Generic placeholder image"></div>   
                    <div class="media">
                        <img class="d-flex align-self-end mr-3" src="https://pbs.twimg.com/media/ESwTou0WkAELPil?format=jpg&name=large" alt="Generic placeholder image"></div>
                </a>
             </div>

             <div class="col-2"></div>
            </div>
        </div>

        <div class="top-center">
            <div class="row">
                <div class="col-2"></div>

                <div class="col-2">
                    <a href="#" class="top-link">
                        <div class="mediaa">
                            <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTnBiXgAATMbJ?format=jpg&name=large" alt="Generic placeholder image"></div>   
                        <p>moji moji moji moji moji moji moji moji mojimoji moji mojimoji moji moji moji moji moji moji moji mojimoji moji moji moji moji moji moji moji moji moji moji moji moji moji</p>
                    </a>
                </div>

                <div class="col-2">
                    <a href="#" class="top-link">
                        <div class="mediaa">
                            <img class="d-flex align-self-start mr-3" src="https://pbs.twimg.com/media/ESwTkKvXYAAXP8I?format=jpg&name=large" alt="Generic placeholder image"></div>   
                            <p>moji moji moji moji moji moji moji moji mojimoji moji mojimoji moji moji moji moji moji moji moji mojimoji moji moji moji moji moji moji moji moji moji moji moji moji moji</p>
                    </a>
                </div>

                <div class="col-4">
                    <a href="#" class="top-link">
                        <img src="https://pbs.twimg.com/media/ESwTiWvWoAANnvt?format=jpg&name=large" class="img-fluid" alt="Responsive image">
                    </a>
                </div>

                <div class="col-2"></div>
            </div>
        </div>
        
        <div class="top-bottom">
            <form method="get" action="#" class="search_container">
                <input type="text" size="25" placeholder=" search">
                <input type="submit" value="&#xf002">
              </form>
        </div>
    </div>       

</div>

{% endblock content %}

cafein/templates/user/login.html
{% extends 'base/base.html' %}

{% load static %}

<!-- style CSS -->
{% block customCSS %}
    <link rel="stylesheet" href="{% static 'css/user/login.css' %}">
{% endblock customCSS %}


{% block content %}


    <div class="headerr">
        <div class="container">
        </div>
    </div>

    <div class="loglog">
        <div class="container">
            <form class="form-signin" method="POST">
                <input type="hidden" name="csrfmiddlewaretoken" value="oS69skOeZO43oHZJBw29HGD5Ii10JeeaCs1Cuxab4WoVdTYc0lJvstIOKqcUCjNf"> 
                <div class="form-signin-heading"><h2>Login</h2></div>

                <input type="text" class="form-control" name="username" placeholder="Email" required="" autofocus="">
          
                <input type="password" class="form-control" name="password" placeholder="Password" required="">
          
                <button type="submit" class="btn btn-lg btn-secondary btn-block form-btn">Login</button>
          
                <p class="center mt-3">or</p>
                <p class="center"><a href="/user/signup/">New Add</a></p>
              </form>
        </div>
    </div>


{% endblock content %}